var products=[{
    "id":0,
    "title":"-- Select Product--",
    "price":"",
    "description":"",
    "brand":"",
    "image":"images/No_Image.png"
},{
    "id":1,
    "title":"Gul Ahmed 1 ",
    "price": 4035,
    "description":" Black  GUL 90000 Plus Unstitched Fabric Cotton.",
    "brand":"Ideas ",
    "image":"images/Gul 1.jpg",
},{
    "id":2,
    "title":"Gul Ahmed 2 ",
    "price":4091,
    "description":"Brown Hitex Cool Unstitched Fabric Cotton-LF.",
    "brand":"Ideas",
    "image":"images/Gul 2.jpg",
},{
    "id":3,
    "title":"Gul Ahmed 3",
    "price":4221,
    "description":"Green Starlight Cotton Unstitched Fabric Cotton-LF.",
    "brand":"Ideas",
    "image":"images/Gul 3.jpg",
},{
    "id":4,
    "title":"Gul Ahmed 4",
    "price":4046,
    "description":" Blue Doria SP 01 Unstitched Fabric Cotton-LF.",
    "brand":"Ideas",
    "image":"images/Gul 4.jpg",
},{
    "id":5,
    "title":"Gul Ahmed 5",
    "price":4244,
    "description":"Gray Opus Aries Unstitched Fabric Blended-LF.",
    "brand":"Ideas ",
    "image":"images/Gul 5.jpg",
},{
    "id":6,
    "title":"Junaid Jaamshed 1",
    "price":8600,
    "description":"GREEN COTTON KAMEEZ SHALWAR | JJKS-S-32824.",
    "brand":"J.",
    "image":"images/Junaid 1.jpg",
},{
    "id":7,
    "title":"Junaid Jaamshed 2",
    "price":7400,
    "description":"BROWN COTTON KAMEEZ SHALWAR | JJKS-S-37783.",
    "brand":"J.",
    "image":"images/Junaid 2.jpg",
},{
    "id":8,
    "title":"Junaid Jaamshed 3",
    "price":9600,
    "description":"BLACK COTTON KAMEEZ SHALWAR | JJKS-S-32823.",
    "brand":"J.",
    "image":"images/Junaid 3.jpg",
},{
    "id":9,
    "title":"Junaid Jaamshed 4",
    "price":7600,
    "description":"CREAM BLENDED KAMEEZ SHALWAR | JJKS-S-34537.",
    "brand":"J.",
    "image":"images/Junaid 4.jpg",
},{
    "id":10,
    "title":"Junaid Jaamshed 5",
    "price":7500,
    "description":"HATCHED BROWN COTTON KAMEEZ SHALWAR | JJKS-S-32746.",
    "brand":"J.",
    "image":"images/Junaid 5.jpg",
}]